### ISSUE TITLE
Map Generation

### ISSUE THREAD

**Issue by SreehariRamesh** [UQdeco2800/2021-ext-studio-1#10]
# **Description**
**Task:** Map Generation(#1).
**Feature:** Designing and building the map (bridge) for the overall game.(#2)
 
On starting a level, the game will generate a random, procedurally-generated map, i.e., our team will work on the overall map structure for the game. This will be a 2D multi-lane rainbow bridge (Bifrost) which will help other teams with the foundation to a add their features e.g. obstacles and power ups, for an intense, addictive and interactive play. Our team will design this bridge for the character to run and attain their achievements while trying to win by avoiding/destroying enemies.
 
## **Example (optional)**
- **Part**: The one of the most important features of the game, will be the environment and thus a layout i.e., a bridge where all the actions will take place or simply where everything in the game will revolve around. Thus, since it is a Ragnarok theme game, we will mostly have only one map, I.e., a RAINBOW BRIDGE.

# **Dependencies**
NONE, as it provides a basis for other teams and the game to be developed upon
 

# **Milestones**
List of steps that need to be completed for this task.

- [x] Designing a basic map layout,(in this case a rainbow bridge)(Aug. 19)
- [x] Coding the map according to the designed layout(Aug. 21)
- [x] Addition of multiple lanes for player movement(Aug 24)
- [x] Integration of map with other features in the game(Aug 26)
- [x] Testing the features(Aug 28)
**Completion Deadline:** Aug. 31
 
# **Documentation**
- [Main Description of Feature](https://github.com/UQdeco2800/2021-ext-studio-1/wiki/Map-Generation)
- [Designing the Map](https://docs.google.com/document/d/1oVmqdIcaTBYCaOxTy4miXennvL-x4UceYbQrRJ_c8n8/edit#heading=h.6q9znerhuz59)
- [Coding the Map](https://docs.google.com/document/d/1UcLQCCrzZ101DwDCi9Ao9Bn80CqKCRiFJBtvCljZkAc/edit#)
- [Individual Contributions](https://docs.google.com/document/d/1uUmu_sLDgPrILHiGo1BAOxf0ELBDqfQcSyXEfnfZnh4/edit)

 
# **Member**
- Sreehari Ramesh (@SreehariRamesh ) (Sreehari Ramesh)
- Rimanshu Dhapodkar (@Rimanshuu ) (Rimanshu)
- Adrian Low (@AdrianLSY) (Adrian Low)
- Sheershak Kumar (@Sheershak007 ) (Sheershak Kumar)
- Sean Marshall (@Abstrusei ) (Sean)
- Jiazheng Ji (@s4425028 ) (Jiazheng Ji)

**Comment by AdrianLSY** [comment]
Hi, please add me as a participant. Thanks!

**Comment by uqnjain** [comment]
The ticket looks good. Make sure you keep it up to date with your progress. I look forward to your documentation!
