### ISSUE TITLE
Task Ticket - Health System Animation

### ISSUE THREAD

**Issue by adrienerice** [UQdeco2800/2021-ext-studio-1#12]
## **Description**
**Task**: Health System Animation (#12)
**Feature:** Player Health System (#6 )

Designing and Animating the health bar and notifications of health depletion.

## **Examples**
- **Heart Health Bar Animation**: When the players health is updated in the game, the health bar and hearts within the health bar are updated accordingly and are animated in a smooth manner. 
- **Health Notification Animations**: Animating health depletion notifications so that when the player loses a heart, a notification pops up and disappears. 

## Dependencies/Dependers
- [x] Dependency 1: Implementation of Player Health System Functions (#16) -- Player Health System Functions needs to be implemented for the animations to work on cue

## Milestones
List of steps that need to be completed for this task.

- [x] Drafting and Designing of Heart Health Bar (Aug. 22)
- [x] Drafting and Designing of Health Notifications (Aug. 22)
- [x] Creating a table for the player health notification to exist in (Aug. 22)
- [x] Notification animation created in libGDX and implemented (Aug. 26)
- [x] Heart Health Bar animation created in libGDX and implemented (Aug. 26)
- [x] Implementation of call/trigger function from the UpdatePlayerHealthUI for the heart health bar (Aug. 26)
- [x] Implementation of call/trigger function from the UpdatePlayerHealthUI for the notifications (Aug. 29)

## Members
Adriene Rice (@adrienerice)
Wenqiang WANG(@jerryADwang)
Isaac Oreth (@isaac-oreth)
Yamin Zhang (@GmKls)
