### ISSUE TITLE
Task Ticket - Consistency of Screen Backgrounds

### ISSUE THREAD

**Issue by adrienerice** [UQdeco2800/2021-ext-studio-1#129]
## **Description**
**Task**: [Consistency of Screen Backgrounds](#129)

Redesigning screen backgrounds to maintain consistency across the game. Including the main game screen, game over screen, win screen, and settings screen.

## Dependencies
- [x] Dependency 1: [Win Screen](#60) : Win screen must be functional in order to make changes
- [x] Dependency 2: [Lose Condition/Game Over Screen](#26) : Game Over screen must be functional in order to make changes
- [x] Dependency 3: Settings screen: Settings screen must be functional in order to make changes

## Milestones
List of steps that need to be completed for this task.
- [x] Implementation of space background onto respective screens (Oct. 13)
- [x] Change game over visual text to better contrast with the new backgrounds (Oct. 13)
- [x] Fixing the layout of the win screen and game over screen (Oct. 15)
- [x] Change main game background from pink to black (Oct. 15)
- [x] Adding coin collector visual onto the main screen (Oct. 15)
- [x] Change main game exit button to exit buttons consistent with other buttons in the game (Oct. 15)

## Members
Adriene Rice (@adrienerice)
Isaac Oreth (@isaac-oreth)
Yamin Zhang (@GmKls)

**Comment by adrienerice** [comment]
UPDATE: I have changed both the win screen and the game over screen background to the space background seen on the main menu. Additionally I have changed the game over visual text to a lighter shade of pink, as it was very difficult to see with the way it originally contrasted with the space background.
