### ISSUE TITLE
Player Interaction (Sprint 4)

### ISSUE THREAD

**Issue by Vermouth10** [UQdeco2800/2021-ext-studio-1#131]
# **Description**
**Feature:** Improve Player Interaction in the Game
 
The purpose of this task is to improve player interaction in the game. It mainly involves redesigning the new character animations, that is, changing the character facing to the player from the front of the character to the side. Some new animation effects will be added, such as death animation, and some bugs left by the previous sprints will be modified, such as duplication of background music.
For the redesign of character animations, it means that all the animations need to be redesigned, including character running, attacking, collecting coins, gaining the buff and gaining the debuff. All animation effects must face to the player from the side of the character so that the player can acquire a better gaming experience.
Add the death animation effect to the character. When the player is attacked, the character will lose a heart. When the player loses all the hearts in a game, the character will trigger the death animation, that is, the character will lie on the ground and bleed a lot.
Solve the problem of duplication of background music. In the previous sprint, the player clicks restart after death, and repeated background music will appear after the game restarts. This problem will be solved in this sprint.
Set an attack frequency. After discussion, if the player keeps using the attack button, the player will never be attacked by the enemy, and even feel boring. So in this sprint, the player will set a limit on the attack frequency, so as not to make the player feel bored.

## **Example (optional)**
- **New animation of running**: The character will run facing to the right instead of facing to the player.
- **New animation of attack**: Design a new attack animation to make it look more reasonable.
- **Attack frequency**: Set a limit for the player's attack frequency, for example, they can only attack once in two seconds.
 

# **Sprint4**
## **Dependencies**

- Dependency 1 - Enemies(#2) -- Players will interact with enemies
- Dependency 2 - Map content (#9) -- Players will have different animations when they encounter different obstacles. eg. coins, bread, diamonds, stones etc

## **Milestones**
- [ ] Set the attack frequency (Oct.8)
- [ ] Solve the duplication of background music (Oct.10)
- [ ] Design new running animation (Oct.10)
- [ ] Implement death animation (Oct.12)
- [ ] Design new attack animation (Oct.14)
- [ ] Design new coin animation (Oct.14)
- [ ] Design new buff animation (Oct.14)
- [ ] Design new debuff animation (Oct.14)
- [ ] Implement all the new animations (Oct.15)
- [ ] User testing (Oct.17)

 

 
# **Member**
- Jiahao Tian (@tonitian) 
- Ruihao REN (@Vermouth10) (Ruihao Ren)
- Linzichang Ding (@LinzichangDing) (linzichang)
- Binglan Huang (@Sirius7777) (Binglan Huang)
- Yi Peng(@Y1iP)
