### ISSUE TITLE
Voice over for screens and modify countdown timer + repositioning character lanes.

### ISSUE THREAD

**Issue by Rimanshuu** [UQdeco2800/2021-ext-studio-1#132]
## Description

Since this is the last sprint, there are not many features to implement, rather in this sprint we are mostly going to polish the game to provide best user experience. So we, team 4, are going to add a good amount of improvements, adjustments and additions towards existing major implementations of the game. This indeed is intended to enhance user experience which in fact is the purpose of Sprint 4. The tasks we have planned can be seen under milestones...
## Dependencies

-  Dependency 1: GStory screen (Story Screen + Minor Adjustments/Tweaks #82 ) -- Adding voice over to the story screen should be a good feature to have to enhance user experience.

- Dependency 2: Countdown timer (Visualising Countdown Timer #72) -- The timer should be repositioned in a way that it does not interfere the game screen and the game visually looks cleaner to the player.

- Dependency 3: Repositioning character lanes (Map Generation #10) -- The lanes implemented in Map Generation for the players and map contents like enemies, obstacles etc. should be repositioned which might potentially fix major bug of the game
 
### Milestones

- [x] Adding voice over for story screen.
- [x] Modification of the countdown timer e.g. better placement.
- [x] Repositioning the character lanes.
- [x] Increasing the game time. 
- [x] Adding skip button to the story screen.
- [x] SUS user testing
- [x] Fixing code smells and bugs

 
## **Documentation**

# Members
Sean Marshall (@Abstrusei)
Rimanshu (@Rimanshuu )
Jiazheng Ji (@s4425028 )
Sreehari Ramesh (@SreehariRamesh)
Sheershak (@Sheershak007 )
Adrian Low (@AdrianLSY )
