### ISSUE TITLE
Team 6 Sprint 4 Feature Ticket

### ISSUE THREAD

**Issue by adrienerice** [UQdeco2800/2021-ext-studio-1#134]
## **Description**
**Task**: [Team 6 Sprint 4 Feature Ticket](#134 )
**Feature:** Addressing game issues and polishing features.

Improving and polishing features worked on in previous sprints and fixing other known issues in the game.

**Improvements to the score system:**
- Displaying final score visual on the game over screen and the win screen
- Fixing the layout of the game over screen (and win screen once final score visual is added) as visuals are currently not correctly aligned
- Displaying the final score on the game over screen and the win screen
- Displaying the +10 visual when picking up a coin and +50 visual when defeating an enemy, currently only displaying the +10 visual
- Making the +10 and +50 visuals disappear after displaying for a short period of time, as it currently remains on the screen indefinitely once triggered.

**Other improvements:**
- Making the win screen, game over (lose condition) screen, and the settings screen all consistent with the main menu screen and the main game screen
- Fixing the issues arising from the game over screen delay function
- Addressing code smells

## Dependencies
- [x] Dependency 1: (#70) -- Coins must be implemented and functioning in game for the +10 visual to be improved/polished.
- [x] Dependency 2: Enemies (#7) -- Enemies must be implemented and able to be killed in the game for the +50 visual to be improved/polished.
- [x] Dependency 3: Score System (#66) -- Score system must be implemented and functional in order to generate a final score to display on the win screen/game over screen.

## Milestones
List of steps that need to be completed for this task.
1. #129 
- [x] Making all screen backgrounds consistent (Oct. 15)
- [x] Displaying final score visual on the game over screen and the win screen (Oct. 15)
- [x] Fixing the layout of the game over screen and win screen (Oct. 15)
2. #98
- [x] Displaying the final score on the game over screen and the win screen (Oct. 15)
3. #135
- [x] Displaying the +10 visual when picking up a coin and +50 visual when defeating an enemy (Oct. 15)
- [x] Making the +10 and +50 visuals disappear after displaying for a short period of times (Oct. 15)
4. #130
- [x] Fixing the issues arising from the game over screen delay function (Oct. 17)
5. Other tasks
- [x] Addressing code smells (Oct. 17)
- [x] Documentation & finalisation to allow for other teams to use the game over screen (Oct. 18)
- [x] **Completion Deadline**: (@ 16:00  Oct. 19)

## Members
Adriene Rice (@adrienerice )
Isaac Oreth (@isaac-oreth)
Luke Hewitt (@FrederickTheGr8)
Wenqiang WANG(@jerryADwang)
Callum Higgins (@electricalengi)
Yamin Zhang (@GmKls)
