### ISSUE TITLE
Task Ticket - Score System +10/+50 Animation Visuals

### ISSUE THREAD

**Issue by adrienerice** [UQdeco2800/2021-ext-studio-1#135]

**Comment by adrienerice** [comment]
## **Description**
**Task**: [Score System +10/+50 Animation Visuals](#135)
**Feature:** [Team 6 Sprint 4 Feature Ticket](#134)

- Displaying the +10 visual when picking up a coin and +50 visual when defeating an enemy, currently only displaying the +10 visual
- Making the +10 and +50 visuals disappear after displaying for a short period of time, as it currently remains on the screen indefinitely once triggered.
- Fixing the issues arising from the game over screen delay function

## Dependencies
- [x] Dependency 1: (#70) -- Coins must be implemented and functioning in game for the +10 visual to be improved/polished.
- [x] Dependency 2: Enemies (#7) -- Enemies must be implemented and able to be killed in the game for the +50 visual to be improved/polished.


## Milestones
List of steps that need to be completed for this task.
- [ ] Displaying the +10 visual when picking up a coin and +50 visual when defeating an enemy (Oct. 15)
- [ ] Making the +10 and +50 visuals disappear after displaying for a short period of times (Oct. 15)
- [ ] Fixing the issues arising from the game over screen delay function (Oct. 17)


## Members
Wenqiang WANG(@jerryADwang)
Yamin Zhang (@GmKls
