### ISSUE TITLE
Team 1 Sprint 4 Feature Ticket

### ISSUE THREAD

**Issue by lijunyao1** [UQdeco2800/2021-ext-studio-1#138]
# **Description**
**Task:** Team 1 Sprint 4 Feature Ticket
**Feature:** Improve the collection (coin) system and health objects. 
The character gets the coins adding to the coin total. The First Aid Kit and Food increasing the health. 
Making the coin count increment when coins touch the player.

# **Dependencies**

- [ ] Dependency 2:Player Interaction (#5)
- [ ] Dependency 3:Player Health System (#6)
- [ ] Dependency 4:Player Scoring System (#66)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Get First Aid Kit and Food increasing health (Oct. 13)
- [x] Get coin count incrementation working (Oct. 15)
- [x] Fix non-animating map contents (Oct. 17)
- [x] Check all new changes on main branch and ensure they are working (Oct. 18)
 
**Completion Deadline:** Oct. 19

# **Member**
- Junyao Li (@lijunyao1) (Junyao Li)
- Max Quirk (@max-quirk) (Max Quirk)
- Feiyu Chen (@fy3344)(Feiyu Chen)

**Comment by max-quirk** [comment]
> > > Hey guys, I'm from the player interaction team. As you know, we are redesigning all the player interaction animations. Just want to confirm how many types of obstacles you will put in the final game and what effects will they have on the player？
> > 
> > 
> > Could you give me a list? Thanks a lot.
> 
> > I'm not very sure. You can check the Wiki Map Contents (https://github.com/UQdeco2800/2021-ext-studio-1/wiki/Map-contents). But I think it's almost finished.

@LinzichangDing Yep just check the Map Contents section in the wiki please, I've updated them all and they are accurate

**Comment by LinzichangDing** [comment]
> > > > Hey guys, I'm from the player interaction team. As you know, we are redesigning all the player interaction animations. Just want to confirm how many types of obstacles you will put in the final game and what effects will they have on the player？
> > > 
> > > 
> > > Could you give me a list? Thanks a lot.
> > 
> > 
> > > I'm not very sure. You can check the Wiki Map Contents (https://github.com/UQdeco2800/2021-ext-studio-1/wiki/Map-contents). But I think it's almost finished.
> 
> @LinzichangDing Yep just check the Map Contents section in the wiki please, I've updated them all and they are accurate

Great! Thanks!
