### ISSUE TITLE
Tutorial page feature ticket v2.0 (team3)

### ISSUE THREAD

**Issue by JiaaoY** [UQdeco2800/2021-ext-studio-1#147]
# **Description**
**Task:** Game tutorial
**Feature:** Continue to improve game tutorial function 
 
The purpose of this task is to provide players with a brief description of game rules. The tutorial will indicate the keys that will be used and their functionalities to play this game.

Where and how to implement:
The tutorial button will be implemented on the main menu screen. When the player clicks on the tutorial button, it will lead him to the tutorial section page, where the player can find all the game instructions.

Rationality:

Tutorials can be important since they are a player's first impression of a game, and an overly tedious tutorial or one that does not allow for player freedom can negatively affect their view of a game. (From Wikipedia.) Also, it can be important, as it could be the most effective way of communication between the game producer with the players. So, it has been decided that the game tutorial will follow the rules:
The best game ever, Super Mario Bros, did not have a game tutorial, it was because its game design is fantastic, and players will eventually (not taking too many tries) understand the gameplay. We may not be able to create that level of game design, but it enlightened us about the game should not have a complicated tutorial. So, the main rules are: the tutorial can be optional, and it will have visuals more than readings.

# **Dependencies**
 
- None
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 Design buttons for switching between different screen
- [x] Step 2 Implement buttons on the tutorial screen
- [x] Step 3  Make tutorial screens for player movement, enemies and map content.
- [x] Step 4 Add content to player movement, enemies and map content screen.

Other Task that needs to be completed
- [x] Improve design of buttons(start, tutorial, setting, exit) by adding a drop shadow
- [x] Integrate newly designed buttons with code
- [x] Improve code to keep the player in the middle of the lane

The overall list of steps that needed to be completed for sprint 3 tasks
- [x] Design buttons for switching between different screen
- [x] Implement buttons on the tutorial screen
- [x] Make tutorial screens for player movement, enemies and map content.
- [x] Add content to player movement, enemies and map content screen.
- [x] Improve design of buttons(start, tutorial, setting, exit) by adding a drop shadow
- [x] Integrate newly designed buttons with code
- [x] Improve code to keep the player in the middle of the lane

**Completion Deadline for sprint 4:** 
- [x] Design buttons for switching between different screens (14 Oct)
- [x] Implement buttons on the tutorial screen (18 Oct)
- [x] Make tutorial screens for player movement, enemies and map content. (18 Oct)
- [x] Add content to player movement, enemies and map content screen. (18 Oct)
- [x] Improve design of buttons(start, tutorial, setting, exit) by adding drop shadow (14 Oct)
- [x] Integrate newly designed buttons with code (14 Oct)
- [x] Improve code to keep the player in the middle of the lane (18 Oct)

 
# **Documentation**

https://github.com/UQdeco2800/2021-ext-studio-1/wiki/Tutorial-Screen
 
# **Member**
- Yan Jiang (@whateverchris) (Yan Jiang)
- Aayush Aggarwal (@The-aayush)(Aayush)
- Runxing Li (@runx1ng) (Runxing Li)
- ZhiRan Huang (@ZhiRanHuang) (ZhiRan Huang(44811910))
- Jiaao Yu(@JiaaoY)(Jiaao)
