### ISSUE TITLE
Task ticket Designing and implementing buttons (team 3)

### ISSUE THREAD

**Issue by JiaaoY** [UQdeco2800/2021-ext-studio-1#148]
## **Description**
**Task**: [Designing and implementing buttons]
**Feature:** [Improving user experience]

Designing the visual elements such as start, tutorial, setting buttons
- The new buttons will appear on the main game screen, tutorial screen and setting screen.

## Dependencies
- None

## Milestones
List of steps that need to be completed for this task.
- [x] Improve design of buttons(start, tutorial, setting, exit) by adding drop shadow (14 Oct)
- [x] Integrate newly designed buttons with code (14 Oct)
- [x] Change the background and the title of main menu screen(14 Oct)

## Members
- Aayush Aggarwal (@The-aayush)(Aayush)
- Jiaao Yu(@JiaaoY)(Jiaao)
