### ISSUE TITLE
Task ticket-Create Tutorial for Ragnarok Racer Game (team 3)

### ISSUE THREAD

**Issue by JiaaoY** [UQdeco2800/2021-ext-studio-1#149]
## **Description**
**Task**: [Create Tutorial for Ragnarok Racer Game]
**Feature:** [Gives a description of game to the player]

Provides a description of the game to the player. Gives instructions about how to play the game.

## Dependencies
- [ ] Dependency 1: (#7) -- Information about Enemies
- [ ] Dependency 2: (#9) -- Information about Map Contents

## Milestones
List of steps that need to be completed for this task.
- [ ] Design buttons for switching between different screens (14 Oct)
- [ ] Create a mock-up page.(14 Oct)
- [ ] Make tutorial screens for player movement, enemies and map content based on the mock-up. (18 Oct)
- [ ] Add content to player movement, enemies and map content screen. (18 Oct)
- [ ] Implement buttons on the tutorial screen (18 Oct)

## Members
- Yan Jiang (@whateverchris) (Yan Jiang)
- Aayush Aggarwal (@The-aayush)(Aayush)
- ZhiRan Huang (@ZhiRanHuang) (ZhiRan Huang(44811910))
- Jiaao Yu(@JiaaoY)(Jiaao)
