### ISSUE TITLE
Task Ticket - Player Interaction Feature Documentations

### ISSUE THREAD

**Issue by LinzichangDing** [UQdeco2800/2021-ext-studio-1#156]
# **Description**
**Feature**: Player Interaction sprint4
**Task**  Sprint4 Documentation

This task is to document all player interaction related features and improvements for Sprint 4.
 
## **Example** 
- Do User testing on the final game
- Wiki Documentation
- UML sketch 
 
# **Milestones**

Sprint4
List of steps that need to be completed for this task.
- [x]  Team wiki documentation (Oct.17) 
- [x] Junit test  (Oct. 17)
- [x] UML sketch   (Oct. 18)
- [x]  Final Check (Oct 18)

# **Member**
-Linzichang Ding (@LinzichangDing 
-Ruihao Ren (@Vermouth10 
- Binglan Huang (@Sirius7777
