### ISSUE TITLE
Task Ticket - Implementation of Player Health System Functions

### ISSUE THREAD

**Issue by adrienerice** [UQdeco2800/2021-ext-studio-1#16]
## **Description**
**Task**: Implementation of Player Health System Functions (#16 )
**Feature:** Player Health System (#6 )

Writing the code for and implementing a basic player health system with usable functions for the game.

## **Examples inside the CombatStatsCompnent.java class**
- **Add Health Functions**: addHealth(int health) -- Adds a specified amount of health to the player's healthpool
- **Function to take damage**: hit(CombatStatsComponent attacker) -- If a player has armour, they will take armour damage based on the attacker's getBaseAttack(), otherwise they will take health damage based on the attacker's getBaseAttack().

## Milestones
List of steps that need to be completed for this task.

- [x] Set/Get Health Function for setting the health of the player (Aug. 22)
- [x] Set/Get Armour functions for setting the armour of the player (Aug. 26)
- [x] Add Health functions for adding health to the player (Aug. 22)

## Members
Luke Hewitt (@FrederickTheGr8)
Callum Higgins (@electricalengi)
