### ISSUE TITLE
Task Ticket - Removal of bugs from sonar cloud and documentation

### ISSUE THREAD

**Issue by The-aayush** [UQdeco2800/2021-ext-studio-1#162]
# **Description**
**Feature**: Removal of bugs from sonar cloud
**Task**  Remove as many bugs from sonar cloud

The task is to do documentation for team 3 for sprint 4 and remove as many bugs from sonar cloud
 
## Dependencies
- None

## Milestones
List of steps that need to be completed for this task.
- [x] Make UML Diagrams for tutorial screen (18 Oct)
- [x] Mention everything in documentation (18 Oct)
- [x] Remove bugs from sonarCloud(18 Oct)

The bugs removed are mentioned [here](https://docs.google.com/document/d/1BB0aUY_pK_zsSIkF_N6ZFmpPV82syVsBnzcar0XWXTM/edit)

## Members
- Aayush Aggarwal (@The-aayush)(Aayush)
