### ISSUE TITLE
Task Ticket - Removal of Code Smells using SonarCloud 

### ISSUE THREAD

**Issue by Sheershak007** [UQdeco2800/2021-ext-studio-1#163]
**Description**
Task: Removal and optimization of code by removing as many code smells as possible.
Feature: Optimisation of Studio code.

In this feature, I will try to remove as many as possible code smells before the mentioned deadline using SonarCloud and then will push it to the local branch and merge it with the main branch. Also will try to remove any unnecessary lines and will try to remove all duplication of code.

**Dependencies**

- None as far.

**Milestones**

- [x] To fix as many code smells as possible.
- [x] Complete the documentation.
- [x] Remove all duplications and info.

Completion Deadline: Oct 19th

Documentation
Here is a link for the documentation. Will be updated soon.
...
Member
Sheershak Kumar (@Sheershak007 )
