### ISSUE TITLE
Add voice lines

### ISSUE THREAD

**Issue by AdrianLSY** [UQdeco2800/2021-ext-studio-1#174]
# **Description**
**Task**  Add voice lines to Story screen, Win screen, Lose screen
 
## Dependencies
- None

## Milestones
List of steps that need to be completed for this task.
- [x] Record story screen voice-overs
- [x] Record win screen voice-overs
- [x] record lose screen voice-overs
- [x] implement voice-overs

## Members
- Adrian Low(@AdrianLSY )
