### ISSUE TITLE
Main Menu Screen - Design Tweak

### ISSUE THREAD

**Issue by Abstrusei** [UQdeco2800/2021-ext-studio-1#176]
# **Description**
**Task**  Tweaking the design of the current game screen to make it more visually consistent with the purple-heavy space themed game. This is a collaborative task between Team 3 and Team 4. In particular, Sean and Aayush.
 
## Dependencies
- None

## Milestones
List of steps that need to be completed for this task.
- [x] Design potential main menu screens
- [x] Swap old starry background
- [x] Swap main menu heading text 

## Members
- Sean (@AdrianLSY )
- Aayush Aggarwal (@The-aayush)(Aayush)
