### ISSUE TITLE
Win Condition

### ISSUE THREAD

**Issue by AdrianLSY** [UQdeco2800/2021-ext-studio-1#25]
## Description

Task: Win Condition
Feature: Develop a win condition and ‘winning’ screen

A game needs a win condition to give the player a goal/reason to play the game, When the player survives the incoming waves of obstacles/enemies for 1 minute, the game ends and the player wins, This will trigger the win condition and display a separate screen displaying some cutscene (eg. Mario when he reaches the end of the level and captures the flag)..

## Dependencies
Map Generation (#10 )

## Milestones

- [x] Implement a timer in the game, (Sept. 6)
- [ ] Display a timer/distance left on the game screen (Sept. 8)
- [ ] Create a new end screen to display to the player if the timer ends (Show a game screen with a short cutscene with a winning message) (Sept 13)

Completion Deadline: Sept. 15

## Members
Sreehari Ramesh (@SreehariRamesh )
Rimanshu Dhapodkar (@Rimanshuu )
Adrian Low (@AdrianLSY )
Jiazheng Ji(@s4425028 )
Sean Marshall (@Abstrusei )
Sheershak Kumar (@Sheershak007)

**Comment by uqnjain** [comment]
Hey everyone! I thought you were working on integrating the rainbow bridge/ creation of multiple game screens? Also, I think Team 6 is constructing the end screen. You might want to talk to them to avoid any possible overlap of work.

**Comment by AdrianLSY** [comment]
> 
> 
> Hey everyone! I thought you were working on integrating the rainbow bridge/ creation of multiple game screens? Also, I think Team 6 is constructing the end screen. You might want to talk to them to avoid any possible overlap of work.

We are going to work with other teams with integration. We think we can work on this feature ticket in addition to supporting feature integration, with regards to multiple game screens; we are not utilizing multiple game screens for the the game and the bulk of the gameplay is done on the rainbow bridge screen.

After looking at team 6 task tickets, we see that they are working on a death screen rather than an end-game win screen so I don't think there is any overlap of work.

**Comment by uqnjain** [comment]
Perfect. Just make sure that the entire team gets to contribute equally and don't forget to add wiki links to your ticket (as needed).

**Comment by adrienerice** [comment]
Hey guys, from the studio today it sounded like you guys were making some great progress with the win screen! As discussed, our team will provide you with the restart and exit buttons to ensure consistency on both screens, I thought I would also share the draft for the game over visual text so that we can also keep the consistency with that as well, let me know if you have any input!
![Sprite-0007 2](https://user-images.githubusercontent.com/87960378/132505070-1979b7ee-385e-4028-a90f-8bd1fd920508.png)

**Comment by Abstrusei** [comment]
That's cool @adrienerice. Digging the pixel art look. Ties in really nicely with the rest of the game. We'll try follow suite.

**Comment by adrienerice** [comment]
Thanks! We also have the restart and exit buttons ready to go for you guys to use:
![btn_restart1](https://user-images.githubusercontent.com/87960378/132940353-f131de41-1542-44ba-a421-6270b67a9747.png)
![btn_exit1](https://user-images.githubusercontent.com/87960378/132940354-9a948399-94a3-47eb-a4ce-75713aeed69d.png)

**Comment by Abstrusei** [comment]
![Win-screen-2-pixel-font-2-newBtns](https://user-images.githubusercontent.com/22090530/132942001-4fab1561-08e2-47a4-aa4c-f1fadaa5e3d2.png)
Cool! Here's a quick PS incorporating your button designs into our win screen. Doesn't look too bad
