### ISSUE TITLE
Lose Condition/Game Over Feature Ticket

### ISSUE THREAD

**Issue by adrienerice** [UQdeco2800/2021-ext-studio-1#26]
## **Description**
**Task**: [Lose Condition/Game Over Feature Ticket](#26).
**Feature:** Providing a game over/death screen when the player returns zero health and the round of play is under the one minute mark.

Creating a death screen to symbolise that the game has been lost and is over. Triggering when the players health has been completely depleted and is under the minute mark, the main game will revert to this screen, where the screen will state game loss, and will provide options for the player to either restart, or exit to the main menu of the game. Will include UI/UX representation of character death, restart and exit buttons, as well as functionality of the restart and exit buttons. May include a scoring system.

## **Examples**
- **Loss condition**: As the player suffers hits from enemies, their health will decrease to the point of zero/no health, and the round of play is under the minute mark, at this point the game cannot continue as the player should be considered dead. The loss condition is satisfied where the player has zero hearts. When the loss condition is satisfied the game will be over.
- **Scoring**: Each second of survival in game = 5 score points.

## Dependencies
- [x] Dependency 1: Main Game Interface/Starting Screen -- Game over screen must be able to revert to starting screen/main menu screen if the exit button is pressed.
- [x] Dependency 2: Player Health System (#6) -- Loss condition and reversion to game over screen requires implemented health system to define how the player may get to zero health.
- [x] Dependency 2: Win Condition (#25) — The win condition of surviving over a minute needs to be implemented and some screen elements need to be consistent with our designed screen elements.

## Milestones
List of steps that need to be completed for this task.

- [x] Initial game over functions and implementation (Sep. 08)
- [x] UI/UX implementation of game over screen (Sep. 08)
- [x] UI/UX implementation of restart and exit buttons (Sep. 08)
- [x] UI/UX implementation of scoring system (Sep. 12)
- [x] Restart and exit button functionality and implementation (Sep. 12)
- [x] Scoring system functionality and implementation (Sep. 12)
- [x] Documentation & finalisation to allow for other teams to use the game over screen (Sep. 13)
- [x] **Completion Deadline**: (@ 16:00  Sep. 14)

## Members
Adriene Rice (@adrienerice )
Isaac Oreth (@isaac-oreth)
Luke Hewitt (@FrederickTheGr8)
Wenqiang WANG(@jerryADwang)
Callum Higgins (@electricalengi)
Yamin Zhang (@GmKls)

**Comment by uqnjain** [comment]
Hi Team! Your ticket looks good. Could you please have a look at Team 4's ticket to ensure there is no overlap of work?

**Comment by adrienerice** [comment]
> Hi Team! Your ticket looks good. Could you please have a look at Team 4's ticket to ensure there is no overlap of work?


Thanks for that, I have looked at the ticket and it appears that the win condition screen only displays where the player has been able to survive for >= 1 minute. I have updated the ticket to specify that the player will only lose and display the loss condition screen if the players health reaches zero in under 1 minute, this should avoid overlap.
