### ISSUE TITLE
Task ticket - Character Animations and effects

### ISSUE THREAD

**Issue by JiaaoY** [UQdeco2800/2021-ext-studio-1#28]
## **Description**
**Task**:Character Animations and effects(#28)
**Feature:** player movement(#3)

Different animations and effects will be shown on the screen when players are moving.

## Milestones
List of steps that need to be completed for this task.

- [ ] Making and implementation of animations.

- [ ] Movement effects

## Completion deadline for Sprint 2 (character Adjustment and effects)

- [ ] Making and implementation of animations. (Sep. 11)

- [ ] Movement effects. (Sep. 14)

## Members
- Yan Jiang (@whateverchris) (Yan Jiang)
- Aayush Aggarwal (@The-aayush)(Aayush)
- Runxing Li (@runx1ng) (Runxing Li)
- ZhiRan Huang (@ZhiRanHuang) (ZhiRan Huang(44811910))
- Jiaao Yu(@JiaaoY)(Jiaao)

**Comment by JiaaoY** [comment]
player_interaction team will take over the effects

**Comment by JiaaoY** [comment]
animation is created but not implemented
