### ISSUE TITLE
Task ticket - Main screen

### ISSUE THREAD

**Issue by JiaaoY** [UQdeco2800/2021-ext-studio-1#29]
## **Description**
**Task**:Main screen(#29)
**Feature:** player movement(#3)

Make changes for the Main screen(title, start button, exit button, background). Only UI

## Milestones
List of steps that need to be completed for this task.

- [ ] Designing main screen title

- [ ] Designing main screen buttons

- [ ] Designing main screen background

## Completion deadline for Sprint 2 (Main Screen)

- [ ] Designing main screen title (Sep. 14)

- [ ] Designing main screen buttons (Sep. 14)

- [ ] Designing main screen background (Sep. 14)

## Members
- Yan Jiang (@whateverchris) (Yan Jiang)
- Aayush Aggarwal (@The-aayush)(Aayush)
- Runxing Li (@runx1ng) (Runxing Li)
- ZhiRan Huang (@ZhiRanHuang) (ZhiRan Huang(44811910))
- Jiaao Yu(@JiaaoY)(Jiaao)

**Comment by JiaaoY** [comment]
designing is done, but the buttons have not been implemented

**Comment by Abstrusei** [comment]
Hey guys! Thought we could use a slightly different background for the main menu screen which flows better with the rest of the game. Here it is
![space-background](https://user-images.githubusercontent.com/22090530/134771812-df10f94f-0dbc-4acb-a9c1-c92382bd41b0.png)
