### ISSUE TITLE
Task Ticket - Implementation of the Lose Condition/Game Over Screen Functions

### ISSUE THREAD

**Issue by adrienerice** [UQdeco2800/2021-ext-studio-1#30]
## **Description**
**Task**: [Implementation of the Lose Condition/Game Over Screen Functions](#30)
**Feature:** [Lose Condition/Game Over Feature Ticket](#26).

Writing the code for and implementing the functions that make the screen appear when the player loses all health before gameplay has reached the 1 minute mark, as well as implementing functions that allow the use of the restart and exist buttons on the screen. 

## **Examples:*
- **Restart Game Function**: When the button is pressed the game will automatically restart by taking the player to the main game screen and where the game commences
- **Exit Game Function**: When the button is pressed the game will automatically take the player back to the main menu screen where the player may exit the game
- **Trigger Game Over Screen**: When the player satisfies the two requirements for the lose condition: Reaching zero health, and gameplay of under one minute, the game will end and trigger the game over screen.

## Milestones
List of steps that need to be completed for this task.

- [x] Trigger event for the display of the lose condition/game over screen (Sep. 08)
- [x] Functionality of the restart button (Sep. 10)
- [x] Functionality of the exit game button (Sep. 10)

## Members
Luke Hewitt (@FrederickTheGr8)
Callum Higgins (@electricalengi)
Wenqiang WANG(@jerryADwang)

**Comment by adrienerice** [comment]
## **Description**
**Task**: Implementation of the Lose Condition/Game Over Screen Functions (#30)
**Feature:** Lose Condition/Game Over Feature Ticket (#26  )

Writing the code for and implementing a basic player health system with usable functions for the game.

## **Examples inside the CombatStatsCompnent.java class**
- **Add Health Functions**: addHealth(int health) -- Adds a specified amount of health to the player's healthpool
- **Function to take damage**: hit(CombatStatsComponent attacker) -- If a player has armour, they will take armour damage based on the attacker's getBaseAttack(), otherwise they will take health damage based on the attacker's getBaseAttack().

## Milestones
List of steps that need to be completed for this task.

- [x] Set/Get Health Function for setting the health of the player (Aug. 22)
- [x] Set/Get Armour functions for setting the armour of the player (Aug. 26)
- [x] Add Health functions for adding health to the player (Aug. 22)



## Members
Luke Hewitt (@FrederickTheGr8)
Callum Higgins (@electricalengi)
