### ISSUE TITLE
Task Ticket - Lose Condition/Game Over Screen Design and Animation

### ISSUE THREAD

**Issue by adrienerice** [UQdeco2800/2021-ext-studio-1#31]
## **Description**
**Task**: [Lose Condition/Game Over Screen Design and Animation](#31).
**Feature:** [Lose Condition/Game Over Feature Ticket](#26).

Designing and Animating the various aspects of the lose condition/game over screen, as well as designing armour in the game.

## **Examples:*
- **Game Over/You Have Died**: This text will be in large pixelated font in the centre of the screen explaining to the user that the game is over and that the player has lost the game.

## Milestones
List of steps that need to be completed for this task.
- [x] Design and implementation of Armour for the health system in the main game (Sep. 08)
- [x] Design and implementation of game over font (Sept. 08)
- [x] Design, Animation and implementation of restart and quit buttons (Sep. 10)
- [x]  Design, Animation and implementation of character death (Sep. 10)
- [x] Design and implementation of the game over screen (Sep. 12)

## Members
Yamin Zhang (@GmKls)
Adriene Rice (@adrienerice )
Isaac Oreth (@isaac-oreth)
