### ISSUE TITLE
Weapons/ Collectables System 

### ISSUE THREAD

**Issue by JiashengLi** [UQdeco2800/2021-ext-studio-1#32]
# **Description**
**Task:** Weapons/ Collectables System(#1).
**Feature:** Weapons and Collectable are generated on the map as part of the content.
 
## **Example (optional)**
- **Contra**: Pick up some special weapons and change the attack method (or just change the attack value)
- **Temple Run**:  Pick up the Gem that appears by chance on the map as collectable and save it in the user data
 
# **Dependencies**
 
- [x] Dependency 1:Map generation (#10)-- the contents based on the map itself.
- [x] Dependency 2:Player Interaction (#5)-- the contents will change the status of player.
- [x] Dependency 3:Player Health System (#6) some contents may influence the health.

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 Design Weapon and collectable function (Sep 14)
- [ ] Step 2 Implement contents entities(Sep 14)
- [ ] Step 3 Implement the contents functions and feature(Sep 14)
- [ ] Step 4 User testing (Sep 14)
 
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Feiyu Chen (@fy3344)(Feiyu Chen)
- JiashengLi (@JiashengLi) (JIASHENG LI)
- Junyao Li (@lijunyao1) (Junyao Li)
- Max Quirk (@max-quirk) (Max Quirk)

**Comment by uqnjain** [comment]
Could you please be specific around the kind of weapons you are designing and how this 'weapons system' will work?

**Comment by JiaaoY** [comment]
Hi, we are from team 3, formerly known as the movement team, if you can kindly provide a description of your contents would be great and appreciated, as we are going to implement them on the tutorial page, it can include such as an image, the name of it, what does it do etc. Thanks.
