### ISSUE TITLE
Winning Screen

### ISSUE THREAD

**Issue by AdrianLSY** [UQdeco2800/2021-ext-studio-1#34]
## Description

Display a winning screen when a player completes the game. Specifically, this win screen is to appear after the player has survived 1 minute on  the bifrost. Once the player achieves this, the winning screen will be displayed - giving them the option to restart the game or exit to the main menu.

# Examples:

When the timer runs out, switch to a win game screen

#Milestones

- [x] Finalize the winning screen design
- [x] Code winning screen according to the final design
- [x] Trigger the win screen once the win condition is met (timer ends)
- [x] Modify Game timer #33 to switch screen when it ends
- [x] Add buttons that return to main menu / new game

# **Documentation**
- [Main Description of Feature](https://github.com/UQdeco2800/2021-ext-studio-1/wiki/Winning)
- [Designing the Win Screen](https://docs.google.com/document/d/18FFfw8jv1q_ftCDkDn1W_aV5mUCswhhaNuM3sQu6eqY/edit#heading=h.6q9znerhuz59)
- [Coding the Win Screen/Win Condition](https://docs.google.com/document/d/1e_0cHX0poZVOzMte4W6X0NZ_9s2zQQo87O9gOaVMy1Q/edit)
- [Team 4 - Design Overview](https://github.com/UQdeco2800/2021-ext-studio-1/wiki/Concept-Art-and-Idea-iterations)
- [Individual Contributions](https://docs.google.com/document/d/1e_0cHX0poZVOzMte4W6X0NZ_9s2zQQo87O9gOaVMy1Q/edit)

# Members

Adrian Low (@AdrianLSY )
Sean Marshall (@Abstrusei )
Jiazheng Ji (@s4425028 )

**Comment by Abstrusei** [comment]
Win Screen design is complete and I have worked closely with Team 6 to ensure consistency in design (as they are working on the death/lose screen)

**Comment by Abstrusei** [comment]
Also, I spoke with Ji earlier today and he is finished coding the win screen design in java. Not sure if he has pushed his changes yet.
