### ISSUE TITLE
Player movement feature ticket by Team 3 Hidden Asian Magic

### ISSUE THREAD

**Issue by JiaaoY** [UQdeco2800/2021-ext-studio-1#4]
# **Description**
**Task:** Player movement(#3).
**Feature:** [How player would move in the game](#3)
 
The purpose of this task is to be able to allow the player to make movements in the game. The movement could be depending on the map and the game mode, base on the current situation, the movement component in this game could include going forward, go to the left/right, jump, and crouch.

Rationality:
Going forward would be the most basic movement throughout the entire game, since the game is going to be a running game.
Since there could be multiple lane, so the player should be able to choose which lane they are running to avoid the obstacle and attack the enemies.
The player needs to jump or crouch to avoid hitting the obstacles. 

Other possibilities: The movement could potentially include going backward. Also, if the game is set in the 3D mode, climbing could be optional.

 
## **Example (optional)**
- *Temple Run**: The player controls being chased by an enemy. The primary theme of the game is an explorer chased from a group of demon monkeys. The player controls a player character, with the perspective behind the player character’s back. While the character is running, the player can swipe left or right to move the character to either side of the screen to collect coins and avoid obstacles.

# **Dependencies**
 
- [ ] Dependency 1 - Map generation (#xx)
- [ ] Dependency 2 - Map content (#xx)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1  Move forward 
- [ ] Step 2  Move to the left/right lane 
- [ ] Step 3  Crouch 
- [ ] Step 4  Jump  
- [ ] Step 5  If 3D map, then climb

**Completion Deadline:** 
 
- [ ] Move forward (Week 5).
- [ ] Move to the left/right lane (Week 6).
- [ ] Crouch (Week 7).
- [ ] Jump (Week 8).
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Yan Jiang (@whateverchris) (Yan Jiang)
- Aayush Aggarwal (@The-aayush)(Aayush)
- Runxing Li (@runx1ing) (Runxing Li)
- ZhiRan Huang (@ZhiRanHuang) (ZhiRan Huang(44811910))
- Jiaao Yu(@JiaaoY)(Jiaao)

**Comment by uqnjain** [comment]
Please add a completion date (one before the end of Sprint 1). This will indicate what we expect your feature team to deliver at the end of sprint two.  Additionally, add date ranges to specify when you expect to complete each of the listed steps. Try to make things specific in the ticket. For instance, will we have multiple lanes in the game?

**Comment by The-aayush** [comment]
@uqnjain  All the tasks and dates for completion of Sprint 1 are updated. Also the dates for further Milestones are also updated.

**Comment by uqnjain** [comment]
What are your deadlines for Sprint 2?

**Comment by JiaaoY** [comment]
> What are your deadlines for Sprint 2?
Sorry, the deadlines were combined, I've just split them up.

**Comment by uqnjain** [comment]
Thank you
