### ISSUE TITLE
JUnit testing Team 4

### ISSUE THREAD

**Issue by Sheershak007** [UQdeco2800/2021-ext-studio-1#40]
**Description**
**Task:**  To provide unit testing for Bridge and lane class.

The main goal of this task ticket is to check the overall quality and testing of the bridge and lane class created by @AdrianLSY in Sprint 1. 
Also to provide the highest quality of our java code, I will perform cleaning of code smells and fixing of few bugs on the sonar cloud once the unit testing is completed.

**Example:**
 After the Junit tests have been written we will try to resolve any tests that get failed and push the updated code, or else if every test passed then move to sonar cloud for cleaning and quality checking.

Milestones
List of steps that need to be completed for this task.

 - [x] Complete checking of Bridge class by JUnit testing (Sep. 11)
 - [x] Complete checking of Lane class by JUnit testing (Sep. 12)
 - [x] Quality checking of code and removing smells from sonar cloud (Sep. 13)
      Completion Deadline: Sep. 14

Member
Sheershak Kumar (@Sheershak007 )
