### ISSUE TITLE
Player Interaction Feature Ticket

### ISSUE THREAD

**Issue by Sirius7777** [UQdeco2800/2021-ext-studio-1#5]
# **Description**
**Task:** [Player Interaction](#5).
**Feature:** [Player Interaction in the Game](#5)
 
This task will determine the player's interaction in the game. Basic interaction methods can include attack, destruction, defense, construction and placement. The way of interaction may change according to the game mode. For example, players will be allowed to attack enemies or place obstacles and traps (SPRINT 2 Onwards) to interfere with them. Destruction allows players to use props to destroy obstacles.
 
## **Example (optional)**
- **Fall Guys (a game)**: In this game, players not only need to avoid obstacles on the way to the end, but also need to fight against their competitors, such as pulling or bumping. These actions will interfere with their enemies' actions and prevent them from going to the end.
- **Attack enemies**: If players don’t have a weapon, they attack the enemy with their fist, and if they get a weapon, they can attack enemies with a weapon. 
- **Touch enemies**: If players touch an enemy and fail to attack, they will receive a health deduction.
- **Encounter Obstacles**: When players encounter an obstacle, it will slow down the movement speed temporarily.
- **Destroy obstacles**: Players can destroy obstacles when they have a weapon.
 
# **Dependencies for sprint1**

- Dependency 1 - Player health system(#6) -- Some interactions may influence player's health
- Dependency 2 - Enemies(#2) -- Players will interact with enemies
- Dependency 3 - Player movement (#4) -- Some interactions depend on player movement
- Dependency 4 - Map content (#9) -- Interaction with obstacles depends on map contents

# **Dependencies for sprint2**

- Dependency 1 - Map Generation(#10) -- Player will interact with the new map
- Dependency 2 - Enemies(#2) -- Players will interact with enemies
- Dependency 3 - Player movement (#4) -- Player interaction and player movement will share some common animations 
- Dependency 4 - Map content (#9) -- Players will have different animations when they encounter different obstacles

# **Milestones for sprint 1**
List of steps that need to be completed for this task.

- [x] #17 (Aug.20)
- [x] #19 (Aug.23) kill enemies by one attack, ghost king(boss) can not be attack in sprint 1
- [x] #14 (Aug.26) obstacles will be created after sprint 1, so the task is cancelled with consent of relevant teams
- [x] #20 (Aug.29)
- [x] Testing (Aug. 30)
 
**Completion Deadline:** Aug. 31
 
# **Milestones for sprint 2**
- [ ] Animation of buff - Design.(Sep.8)
- [ ] Animation of debuff - Design.(Sep.8)
- [ ] Design sound effect for attack, under attack, touch oobstacle and buff.(Sep.10)
- [ ] Implement code of buff animation.(Sep.11)
- [ ] Implement code of debuff animation.(Sep.12)
- [ ] Implement code of lose health animation.(Sep.13)
 
# **Documentation**
- [Player Interaction model research](../wiki/Player-Interaction-model-research)
- [Player Interaction Sprint1](../wiki/Player-Interaction-Sprint-1)
- [Player interaction test plan](../wiki/Team-5---Player-interaction-Sprint-1-test-plan)
- [Player Interaction User Testing](../wiki/Team-5-Player-Interaction-Sprint-1-User-Testing)
 
# **Member**
- Jiahao Tian (@tonitian) 
- Ruihao REN (@Vermouth10) (Ruihao Ren)
- Linzichang Ding (@LinzichangDing) (linzichang)
- Binglan Huang (@Sirius7777) (Binglan Huang)
- Yi Peng(@Y1iP)

**Comment by uqnjain** [comment]
Please remove text that was a part of the template and add your own description (under Dependencies). You could try and be a little more specific about interactions. For instance, how will they attack (punch with a hand/ kick)?

**Comment by manavvbahl** [comment]
**Enemies team**.
guys just wanted to confirm that we shall remove the enemy interaction part from our milestone ? since we have agreed upoun it from todays studio. Enemies team will be working on designing and creating enemy entities. and movement (for further sprints ?).

**Comment by uqnjain** [comment]
Could you please separate your sprint 1 and 2 dependencies?

**Comment by LinzichangDing** [comment]
> Could you please separate your sprint 1 and 2 dependencies?

**Comment by LinzichangDing** [comment]
dependencies updated

**Comment by LinzichangDing** [comment]
> dependencies updated

**Comment by manavvbahl** [comment]
Hey guys wanted to confirm that since you are the interactions team. You guys will be handling the player-enemy interaction right as we had agreed earlier in the sprints.

**Comment by LinzichangDing** [comment]
> Hey guys wanted to confirm that since you are the interactions team. You guys will be handling the player-enemy interaction right as we had agreed earlier in the sprints. I am from Enemies team. I was wondering since the player will be able to kill the enemies. Right ?

yep That's our part
