### ISSUE TITLE
Player Health System Feature Ticket

### ISSUE THREAD

**Issue by adrienerice** [UQdeco2800/2021-ext-studio-1#6]
## **Description**
**Task**: [Player Health System](#6).
**Feature:** The players health and how it would be affected by different things

Creating a Player Health System that will provide a loss condition to the player whenever the player reaches 0 health. Provide the UI/UX representation of player health, and the necessary functionality of the player health system that will be called by others (enemy attacks player, player hits obstacle, etc).

## **Examples**
- **Heart system**: Player starts with a full heart as a representation of their health pool. As a player takes damage, their heart depletes. When it reaches zero the player loses the game and starts from either a designated checkpoint, or the beginning of the game.
- **Armour/buff benefit**: Players may obtain armour or buffs in the game that reduce their damage taken.
- **Major Health Deductions**: If the player encounters a major obstacle (i.e. holes or falling off the bridge) The player will receive the maximum health deduction; Instant death, and therefore loss of the game. 
- **Minor Health Deductions**: If the player encounters a minor map obstacle (i.e. a wall or spikes) the player will receive a minor health deduction (i.e. 1/4 or 1/2 of a heart).
- **Other Health Deductions**: Successful hits to the player by an enemy or player consumption of a harmful potion will result in a health deduction. Health deductions will range in severity (i.e. enemy level/difficulty).
--
- **Player Health Boosts**: The player will get a health boost under certain circumstances, (i.e. killing a number of enemies). ****Second sprint content**

## Dependencies/Dependers
- [x] Depender 1: Enemies (#7) -- Enemy damage requires the player health system.
- [x] Depender 2: Health System Animation (#12) -- Health system animation requires implemented health system 
- [x] Dependency 1: Player Interaction (#5) -- Player Health System effects require player interactions

## Milestones
List of steps that need to be completed for this task.

- [x] Initial player health system implementation (Aug. 22)
- [x] Damage taken functions (Aug. 26)
- [x] UI/animation implementation of health system (Aug. 26)
- [x] Documentation & finalisation to allow for other teams to use the health system (Aug. 29)
- [x] **Completion Deadline**: (@ 22:00  Aug. 31)

## Members
Adriene Rice (@adrienerice )
Isaac Oreth (@isaac-oreth)
Luke Hewitt (@FrederickTheGr8)
Wenqiang WANG(@jerryADwang)
Callum Higgins (@electricalengi)
Yamin Zhang (@GmKls) #

**Comment by uqnjain** [comment]
The ticket looks good. I look forward to reading your documentation (make sure you update those links on your ticket).
