### ISSUE TITLE
Contents animation

### ISSUE THREAD

**Issue by JiashengLi** [UQdeco2800/2021-ext-studio-1#61]
## **Description**
**Feature:** Map contents (#9)

Changed car obstacle to RunesGate, snake to thunderCloud, and built the animation for them.

## Examples 
-Use animation software to build up and down special effects for contents
-Added performance effects to contents

# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 Design Weapon and collectable function (Sep 14)
- [x] Step 2 Implement contents entities(Sep 14)
- [x] Step 3 Implement the contents functions and feature(Sep 14)
- [x] Step 4 User testing (Sep 14)

# **Member**
- JiashengLi (@JiashengLi) (JIASHENG LI)
