### ISSUE TITLE
Implement Weapons and collectables

### ISSUE THREAD

**Issue by JiashengLi** [UQdeco2800/2021-ext-studio-1#62]
## **Description**
**Feature:** Map contents (#9)

Added new contents: weapon and collectables, spawned in the rainbow bridge map.
Weapon will increase user's status or heal their health, collectable will be as an achievement.

## Examples 
-Player can pick them up as items
-Every contents hold distinct feature
-Use animation software to build up and down special effects for collectables

# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1 Design Weapon and collectable function (Sep 14)
- [x] Step 2 Implement contents entities(Sep 14)
- [x] Step 3 Implement the contents functions and feature(Sep 14)
- [x] Step 4 User testing (Sep 14)

# **Member**
- JiashengLi (@JiashengLi) (JIASHENG LI)
