### ISSUE TITLE
Score System Feature Ticket

### ISSUE THREAD

**Issue by adrienerice** [UQdeco2800/2021-ext-studio-1#66]
## **Description**
**Task**: [Score System Feature Ticket](#66)
**Feature:** A score system which updates as the player progresses through the game, as well as integer point increases when the player kills enemies and collects coins. 

Creating a score system when the player makes positive progression in the game. This may be achieved in a variety of different ways, and the scoring system will consist of two components: A Progression Bar, and a Point Collection Function. 

Progression Bar:
As the player progresses through the game by surviving for a period of time (i.e. not losing all health), the progression bar will update and will display how close the player is to game completion (winning the game). 

Point Collection:
Points can be earned in two ways: Attacking and successfully killing enemies, and collecting coins. Killing enemies and collecting coins have a fixed integer value (i.e. 50 points per enemy killed, 50 points for each coin collected). The point collector will return the value of the accumulated points earned throughout a single run of the game. Additionally, when the game comes to an end, whether by winning or losing, the final accumulation of all points earnt in the single run of the game will be presented on the win/lose screen as a final score/high score. 

This feature will include UI/UX representation of the progression bar and the point collector as they are displayed within the main game, as well as the final score achieved derived from the point collector, displayed on the win or lose screen.

## **Examples**
- **Point Collection**: Each enemy kill is worth 50 points
- **Point Collection**: Each coin collected is work 10 points
- **Progression bar**: The longer the player survives without dying, the more complete the progression bar will become, until becoming completely full after 1 minute, which will then result in the end of the game (win condition).

## Dependencies
- [x] Dependency 1: (#70  ) -- Coins must be implemented and functioning in game for the point collection function to work with the coins.
- [x] Dependency 2: Enemies (#7) -- Enemies must be implemented and able to be killed in the game for the point collection function to work with defeating enemies.
- [x] Dependency 2: Win Condition (#25) — The win condition of surviving over a minute needs to be implemented and functional as the progress bar depends on this/these functions.

## Milestones
List of steps that need to be completed for this task.
- [x] Coding for the delay of the game over screen (Sep. 21)
- [x] Initial point collection functions and implementation (Sep. 21)
- [x] UI/UX implementation of points collector visual for main game (Sep. 21)
- [x] UI/UX implementation of points collector visual for win/lose screen (Sep. 21)
- [x] UI/UX implementation of +50 visual text when  player earns points (Sep. 21)
- [x] Animating the +10 and +50 visual text (Sep. 21)
- [x] Documentation & finalisation to allow for other teams to use the game over screen (Oct. 04)
- [x] **Completion Deadline**: (@ 16:00  Oct. 05)

## Members
Adriene Rice (@adrienerice )
Isaac Oreth (@isaac-oreth)
Luke Hewitt (@FrederickTheGr8)
Wenqiang WANG(@jerryADwang)
Callum Higgins (@electricalengi)
Yamin Zhang (@GmKls)

**Comment by manavvbahl** [comment]
Hey Guys, i am from #7. One thing that i found out that your dependency on us is no more ig or atleast not for the score system probably. Since now the Interactions team takes on enemies interaction and its functionality. Actually interactions team is responsible for the player-enemy interaction in the game.

**Comment by manavvbahl** [comment]
Am i correct btw ?

**Comment by jerryADwang** [comment]
> Am i correct btw ?

Thanks let us know, already edited it.

**Comment by LEONBARBAR** [comment]
Hi, guys. I am from enemy team . We tripled the  size of ememy but it will not affect the health system. Does anyone know how to do it and help us to fix it?

**Comment by FrederickTheGr8** [comment]
> 
> 
> Hi, guys. I am from enemy team . We tripled the size of ememy but it will not affect the health system. Does anyone know how to do it and help us to fix it?

Hrm I am unsure why size would effect it, as long as the enemy is calling the public void hit(CombatStatsComponent attacker) within the CombatStatsComponent. So you're saying when you increase the physical size of the enemy it stops it from dealing damage?

**Comment by manavvbahl** [comment]
> > Hi, guys. I am from enemy team . We tripled the size of ememy but it will not affect the health system. Does anyone know how to do it and help us to fix it?
> 
> Hrm I am unsure why size would effect it, as long as the enemy is calling the public void hit(CombatStatsComponent attacker) within the CombatStatsComponent. So you're saying when you increase the physical size of the enemy it stops it from dealing damage?

**Comment by manavvbahl** [comment]
> > Hi, guys. I am from enemy team . We tripled the size of ememy but it will not affect the health system. Does anyone know how to do it and help us to fix it?
> 
> Hrm I am unsure why size would effect it, as long as the enemy is calling the public void hit(CombatStatsComponent attacker) within the CombatStatsComponent. So you're saying when you increase the physical size of the enemy it stops it from dealing damage?

Exactly

**Comment by manavvbahl** [comment]
The only change we made since last time was just adding setscale() method to the spawnghostking class in rainbowbridge.java for increasing the size of enemy. With this one change, it does not affect health update now. This is particularly for the dragon enemy (Ghostking) residing into the second lane from the top.

**Comment by FrederickTheGr8** [comment]
> 
> 
> The only change we made since last time was just adding setscale() method to the spawnghostking method in rainbowbridge.java for increasing the size of enemy. Thats it. With this one change, it does not affect health update now. This is particularly for the dragon enemy (Ghostking) residing into the second lane from the top.
> source/core/src/main/com/deco2800/game/areas/RainbowBridge.java

I will look into this along with another bug we are currently experiencing where the death screen is not showing up.

**Comment by manavvbahl** [comment]
Thanks a lot guys as suggested. The setscale() and setscaledcollider() methods were applied to the enemy class to make it function.
