### ISSUE TITLE
Improvent of map contents feature ticket(Sprint 3)

### ISSUE THREAD

**Issue by JiashengLi** [UQdeco2800/2021-ext-studio-1#69]
# **Description**
**Task:** Improvement of contents(#9).
**Feature:** We plan to divide this sprint into two categories, namely, the uniqueness of the content function and the link and interaction with other features.

For every interaction, there should be new innovations at the design level, such as the establishment of an animation for destruction of the obstacle.

At the same time, optimize the movement of content to ensure that each content is connected to the correct and successful interaction function.Contents will spawn randomly from each line with a reasonable values.

At present, we have established: obstacles, props, weapons, collectable. Among them, there are many kinds of obstacles, and they will be planned to give players different degrees of damage. The props will give players different levels of health recovery. The weapon will consider to start a cooperation with the player interaction team, and we will create new shapes after picking up the weapon to emphasize expressiveness. Collectable will be used as an important prop of the scoring system to interact with the scoring system. That is, every time you pick up a coin or diamond, player will get scores.

## **Example**
- **Feature improvement**: the obstacle interacts with attack function and collision function, the item interacts with pick-up functions and restore the health value. 
- **Animations of contents**:  Collectable system: Whenever the collectable content is collided, it disappears (as a feature of being picked up) and the score increase is recorded.
Weapon system: The most basic is to change the attack animation and appearance for the player. Secondly, we will increase the attack power to realize the function of the weapon, and each weapon (sword, axe, bow) gives different attack power.
 
# **Dependencies**
 
- [x] Dependency 1:Map generation (#10)-- All contents will be generated on the map, through the map to achieve collision and interaction with the player model
- [x] Dependency 2:Player Interaction (#5)-- In order to implement the features of contents, we will cooperate closely with interaction team. At the same time, in order to enhance expressiveness, we need to add animation to the appearance of content when interacting.
- [x] Dependency 3:Player Health System (#6)--The obstacle system may negatively affect the health value, and items and weapons may positively affect the health value
- [x] Dependency 4:Player Scoring System (#66)--Coin and diamond will increase the player's score

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 Realize the random and orderly movement of contents (Sep 21)
- [ ] Step 2 Design simple, effective and unique functions for each content(Sep 21)
- [ ] Step 3 Implement the improvement function of contents(Sep 24)
- [ ] Step 4 Adding new interactive pictures(Sep 24)
- [ ] Step 5 Adjust the interaction with other teams(Oct 5)
- [ ] Step 6 User testing (Oct 5)
 
# **Member**
- Feiyu Chen (@fy3344)(Feiyu Chen)
- JiashengLi (@JiashengLi) (JIASHENG LI)
- Junyao Li (@lijunyao1) (Junyao Li)
- Max Quirk (@max-quirk) (Max Quirk)
