### ISSUE TITLE
Player Interaction (Sprint 3)

### ISSUE THREAD

**Issue by LinzichangDing** [UQdeco2800/2021-ext-studio-1#70]
# **Description**
**Feature:** Improve Player Interaction in the Game
 
The purpose of this task is to improve player interactions in the game. It involves implementing new interactions like coin collection and death animation. Animations designed in the first two sprints like touch, attack and buff will be improved in this sprint as well. 
The coin collection feature allows the player to interact with coins. Each time the player touches a coin, the coin will disappear and a coin will show above the player's head. The total number of coins collected by the player will be counted and recored in the score system.
To avoid multiple characters showing on the screen at the same time, all animations designed in the first three sprints will be integrated into one atlas. The original static character will be removed. Only the dynamic animations will be kept on the screen.
Buff and debuff animation will also be improved. At present, the player lies down every time after touching an obstacle. We will change it to let the player lie down only after he loose all hearts. 
Each animation is designed to play only once. When implementing each animation, the corresponding sound effects will be added as well. 

## **Example (optional)**
- **Player default status**: The player is in the running status by default.
- **Animation switching**: The player will be switched to the default running status after each interaction is finished.
- **Collect coins**: If the player touches a coin, the coin will be collected and recorded into the score system 
 

# **Sprint3**
## **Dependencies**

- Dependency 1 - Enemies(#2) -- Players will interact with enemies
- Dependency 2 - Map content (#9) -- Players will have different animations when they encounter different obstacles. eg. coins, bread, diamonds, stones etc
- Dependency 3 - Score System (#66) -- Number of coins collected by the player should be recorded in the score system

## **Milestones**
- [x] Design coin collection animation (Sep.19)
- [x] Design death animation (Sep.19)
- [ ] Implement coin collection  (Sep.21)
- [ ] Implement death animation  (Sep.21)
- [ ] Remove duplicate player texture (Sep.21)
- [ ] Complete animation switch (Sep.22)
- [ ] Design sound effect for coin collection (Sep.25)
- [ ] Unit testing (Sep.30)
- [ ] User Testing (Oct.1)

 
## **Documentation**
- [Player Interaction Sprint3](../wiki/Player-interaction-Sprint3)
- [Player Interaction Sprint 3 User Testing](../wiki/Team-5-Player-Interaction-Sprint-3-User-Testing)
- [Player Interaction Sprint 3 Test Plan](../wiki/Team-5-Player-Interaction-Sprint-3-Test-Plan)

 
# **Member**
- Jiahao Tian (@tonitian) 
- Ruihao REN (@Vermouth10) (Ruihao Ren)
- Linzichang Ding (@LinzichangDing) (linzichang)
- Binglan Huang (@Sirius7777) (Binglan Huang)
- Yi Peng(@Y1iP)

**Comment by jerryADwang** [comment]
just a brainstorming idea from team 6 **speed up**: when the player press "D"  the enemy's speed or player's speed will increase. I think it might look more interesting to the game.
I'm not sure you'll be interested in it. if not just ignore it.

**Comment by LinzichangDing** [comment]
> just a brainstorming idea from team 6 **speed up**: when the player press "D" the enemy's speed or player's speed will increase. I think it might look more interesting to the game.
> I'm not sure you'll be interested in it. if not just ignore it.

That's a good idea. But it is the enemies moving towards the player, not the player running towards the enemies. Maybe increase the enemies' speed would be more suitable?

**Comment by LinzichangDing** [comment]
> > just a brainstorming idea from team 6 **speed up**: when the player press "D" the enemy's speed or player's speed will increase. I think it might look more interesting to the game.
> > I'm not sure you'll be interested in it. if not just ignore it.
> 
> That's a good idea. But it is the enemies moving towards the player, not the player running towards the enemies. Maybe increase the enemies' speed would be more suitable?

In addition,

**Comment by LEONBARBAR** [comment]
Hi, guys. I am from enemy team . We tripled the  size of ememy but it will not trigger the lose health function. Does anyone know how to do it and could u guys help us with?

**Comment by JiaaoY** [comment]
Hi, I'm from Team 3, formerly known as the movement team, and we are making the tutorial page in this sprint, we were wondering if there is any special effect such as modes of attacking, buff and debuff etc. that we could add to the tutorial page to inform the players.

**Comment by LinzichangDing** [comment]
> Hi, I'm from Team 3, formerly known as the movement team, and we are making the tutorial page in this sprint, we were wondering if there is any special effect such as modes of attacking, buff and debuff etc. that we could add to the tutorial page to inform the players.

we are using space bar for attacking.

**Comment by Y1iP** [comment]
> Hi, I'm from Team 3, formerly known as the movement team, and we are making the tutorial page in this sprint, we were wondering if there is any special effect such as modes of attacking, buff and debuff etc. that we could add to the tutorial page to inform the players.

Adding some screen shot for different effect (animation) like getting hurt or collecting coins to notice player which obs needs to aviod and what obs like aid is helpful

**Comment by Mark-Yuming** [comment]
We encountered difficulties in making the monster hang-up animation. I wonder if your team can help with debugging?

**Comment by Y1iP** [comment]
> We encountered difficulties in making the monster hang-up animation. I wonder if your team can help with debugging?

lets go to discord, i may help u with the animation code.

**Comment by LinzichangDing** [comment]
> > Hi, guys. I am from enemy team . We tripled the size of ememy but it will not trigger the lose health function. Does anyone know how to do it and could u guys help us with?
> 
> Ya guys the kill animation also does not work on the enemy whose size is increased now. I would like u guys to checkout the enemy branch and run the game. For better understanding. The spacebar implementation does not work for the dragon enemy residing onto second lane from the top

Yi Peng should have discussed this with your teammates. Did they solve your problem?

**Comment by manavvbahl** [comment]
Yes after discussing within among ourselves we wanted to inform you guys.
It's working fine now. Thanks.
