### ISSUE TITLE
Visualising Countdown Timer    

### ISSUE THREAD

**Issue by Abstrusei** [UQdeco2800/2021-ext-studio-1#72]
## Description

Display a countdown timer at the top of the screen. Currently, the countdown timer exists. However, there it is not visible to users, nor has it been coded. Specifically, we aim for the timer to countdown from 1:00 (the beginning of the game) to 0:00 . Once this the timer hits 0:00 the win screen appears, signifying the player has survived 1 minute on the bifrost. 

## Dependencies

-  Dependency 1: Game Timer(#25 ) -- We will need to visualise the current game timer, so we will need to use the game timer code 

- Dependency 2: Win Screen (#34) -- The win screen must exist, as it is what pops up after the timer runs out 

- Dependency 3: Win Screen (#75) -- Will be needed to properly test the game timer
 
### Milestones

- [x] Finalize stylistic decisions for the timer e.g. a reasonable placement, font-size, etc...
- [x] Code the visualisation of the countdown timer
- [x] Ensure the timer is being presented properly on the screen
- [x] Test the timer according to the test plans.
 
## **Documentation**
- [Main Description of Feature] 
- [Coding the Timer] 
- [Individual Contributions] 

# Members

Sreehari Ramesh (@SreehariRamesh)
Adrian Low (@AdrianLSY )

**Comment by adrienerice** [comment]
Hey guys, team 6 here, we’ve just noticed with the newly implemented timer in the player stats component has caused the game to automatically quit when the player dies, without showing the game over screen. Our team has mostly fixed the issue, it’s still a bit janky with the code but should be sorted, please have a look at the code so you can decide if you’re happy with it, thanks.
