### ISSUE TITLE
Game tutorial feature ticket - sprint 3

### ISSUE THREAD

**Issue by The-aayush** [UQdeco2800/2021-ext-studio-1#76]
# **Description**
**Task:** Player movement.
**Feature:** Implement a Game tutorial 
 
The purpose of this task is to provide players a brief description of game rules. The tutorial will indicate the keys that will be used and their functionalities to play this game.

Where and how to implement:
The tutorial button will be implemented on the main menu screen. When the player clicks on the tutorial button, it will lead him to the tutorial section page where the player can find all the game instructions.

# **Dependencies**
 
- None
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 Design a tutorial button
- [ ] Step 2  Implement button on the main menu screen
- [ ] Step 3  Integrate it will code

Other Task that needs to be completed
- [ ]  Implement Start, setting, exit button on the main menu screen
- [ ] Integrate start, setting, exit button with respective code 
- [ ] Implement movement animation (on rainbow bridge)

The overall list of steps that needed to be completed for sprint 3 tasks
- [ ] Step 1 Design a tutorial button
- [ ] Step 2  Implement button on the main menu screen
- [ ] Step 3  Integrate it will code
- [ ] Implement Start, setting, exit button on the main menu screen
- [ ] Integrate start, setting, exit button with respective code 
- [ ] Implement movement animation(on rainbow bridge) 

**Completion Deadline for sprint 3:** 
- [ ] Step 1 Design a tutorial button (23rd sep)
- [ ] Step 2  Implement button on the main menu screen (23rd sep)
- [ ] Step 3  Integrate it will code(23rd sep)
- [ ] Implement Start, setting, exit button on the main menu screen (27th sep)
- [ ] Integrate start, setting, exit button with respective code (27th sep)
- [ ] Implement movement animation (on rainbow bridge) (27th sep)
 
# **Documentation**
- * [Spawn Point](https://github.com/UQdeco2800/2021-ext-studio-1/wiki/Spawn-point)
- * [Movements](https://github.com/UQdeco2800/2021-ext-studio-1/wiki/Movements)
- * [Character appearance](https://github.com/UQdeco2800/2021-ext-studio-1/wiki/Character-appearance)

- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Yan Jiang (@whateverchris) (Yan Jiang)
- Aayush Aggarwal (@The-aayush)(Aayush)
- Runxing Li (@runx1ng) (Runxing Li)
- ZhiRan Huang (@ZhiRanHuang) (ZhiRan Huang(44811910))
- Jiaao Yu(@JiaaoY)(Jiaao)

**Comment by manavvbahl** [comment]
https://github.com/UQdeco2800/2021-ext-studio-1/wiki/Enemies. hey guys this is the information regarding enemies which is to be added in tutorial section.
