### ISSUE TITLE
Make improvements to Bridge component

### ISSUE THREAD

**Issue by AdrianLSY** [UQdeco2800/2021-ext-studio-1#79]
## Description

Refactor and make some structural improvements to the Bridge component

### Milestones

- [x] Remove / Modify Bridge.getBounds()
- [x] Create Interface to get y-coordinates of the bridge and lane bounds
- [x] Implement the Interface to Bridge and lane
 
# Members

Adrian Low (@AdrianLSY)
