### ISSUE TITLE
Adjustments and additions 

### ISSUE THREAD

**Issue by Abstrusei** [UQdeco2800/2021-ext-studio-1#82]
## Description

Since we are nearing the end of development, there are not many major features left to implement. As a result, we have taken it upon ourselves to make some adjustments and additions to the current game. By doing so, we hope to enhance the game's code, and create a better experience for players. The tasks we have planned for ourselves can be seen under milestones...

## Dependencies

-  Dependency 1: Game Timer(#25 ) -- We will need to visualise the current game timer, so we will need to use the game timer code 

- Dependency 2: Win Screen (#34) -- The win screen must exist, as it is what pops up after the timer runs out 

- Dependency 3: Win Screen (#75) -- Will be needed to properly test the game timer
 
### Milestones
Timer Related
- [ ] Finalize stylistic decisions for the timer e.g. a reasonable placement, font-size, etc...
- [ ] Code the visualisation of the countdown timer
- [ ] Ensure the timer is being presented properly on the screen
- [ ] Test the timer according to the test plans.

General Tasks
- [ ] Visualise Gametimer(#72)
- [ ] Add new button assets to win screen (to match Team 6) )(#73)
- [ ] Creating Testing Plans and UML diagrams (#75)
- [ ] Fixing Code Smells (#74)
- [ ] Making improvements to bridge component (#79)
- [ ] Creating a background story for the game
- [ ] Creating a screen which displays the background story

 
## **Documentation**
- [Main Description of Feature] 
- [Coding the Timer] 
- [Individual Contributions] 

# Members
Sean Marshall (@Abstrusei)
Rimanshu (@Rimanshuu )
Jiazheng Ji (@s4425028 )
Sreehari Ramesh (@SreehariRamesh)
Sheershak (@Sheershak007 )
Adrian Low (@AdrianLSY )

**Comment by Abstrusei** [comment]
@The-aayush Hey, could we get a 'skip' button as well? Want to add it to the Story Screen in replacement of the 'start' button

**Comment by The-aayush** [comment]
@Abstrusei Hello, here is the skip button we created
![btn_skip1](https://user-images.githubusercontent.com/46275952/135741758-8c081439-45eb-41d8-b2ae-50c9215d19b2.png)
![btn_skip2](https://user-images.githubusercontent.com/46275952/135741768-afa4bc9e-c7cf-4e76-9b28-e466a2d9af12.png)

.
