### ISSUE TITLE
Task Ticket - Implementing Scoring System Functionality

### ISSUE THREAD

**Issue by adrienerice** [UQdeco2800/2021-ext-studio-1#84]
## **Description**
**Task**: [Implementing Scoring System Functionality](#84)
**Feature:** [Scoring System Feature Ticket](#66 )

Writing the code for and implementing the functions that return points when the player kills an enemy or picks up coins, points will increase with each successful kill/coin collection the player makes, and will display the total points earned on the main game screen, and on the game over screen as a final score.

## *Examples:*
- **Coin Collection**: When the player runs towards/over a coin in the game, the player will receive +10 points, and will be displayed on the screen so the player can keep track of how many points they have earned in their game run.
- **Final Score**: When the player finishes the game, either by winning or losing, a final score will be displayed on the appropriate screen, giving the player their final score of all accumulated points earned in that particular game run. 

## Dependencies
- [x] Dependency 1: (#70  ) -- Coins must be implemented and functioning in game for the point collection function to work with the coins.
- [x] Dependency 2: Enemies (#7) -- Enemies must be implemented and able to be killed in the game for the point collection function to work with defeating enemies.

## Milestones
List of steps that need to be completed for this task.
- [x] Implementation of functions for receiving points when certain tasks are completed (Sep. 26)
- [x] Implementation of functions to accrue points as a score and display the score on the screen (Sep. 26)

## Members
Luke Hewitt (@FrederickTheGr8)
Callum Higgins (@electricalengi)
