### ISSUE TITLE
Task Ticket - Design and Animation of Point Collection Visual Elements

### ISSUE THREAD

**Issue by adrienerice** [UQdeco2800/2021-ext-studio-1#85]
## **Description**
**Task**: [Design and Animation of Point Collection Visual Elements](#85)
**Feature:** [Scoring System Feature Ticket](#66 )

Designing the visual elements that make up the point collection system, including:
- The point collection visual that will appear on the main game screen
- The final score visual that will appear on the game over screen
- The +10 visual that will appear above the player as they successfully complete point earning tasks. 

Additionally, implementing these designs into the main game so that they display (are functional), as well as animating the +10 visual, rather than it being a static image. 

## *Examples:*
- **+10 Visual**:  As the player attacks and successfully defeats an enemy, the +10 visual will appear above the players head to indicate that they have gained +10 points for defeating an enemy, the 10 points will also be added to the players overall point collection score.

## Dependencies
- [x] Dependency 3: [Implementing Scoring System Functionality](#84) : The +10 visual relies on the implemented functions of the scoring system in order to trigger the visual above the players head.

## Milestones
List of steps that need to be completed for this task.
- [x] Design of Point Collection Visual for the main game screen (Sep. 25)
- [x] Design of the Final Score Visual for the game over screen (Sep. 25)
- [x] Design of the +10 visual and frames for when the player earns points and in preparation for animation functions (Sep. 25)
- [x] Implementation of Point Collection Visual onto the main game screen (Sept. 27)
- [x] Implementation of the Final Score Visual for the game over screen (Sept. 27)
- [x] Implementation of the +10 visual and frames onto the main game screen (Sept. 27)
- [x] Animation and functionality of the +10 visual appearing above the players head (Sept. 30)

## Members
Adriene Rice (@adrienerice)
Yamin Zhang (@GmKls)
Isaac Oreth (@isaac-oreth)
Wenqiang Wang (@jerryADwang)
