### ISSUE TITLE
Task Ticket - Designing and Implementing buttons on Main Menu Screen

### ISSUE THREAD

**Issue by The-aayush** [UQdeco2800/2021-ext-studio-1#87]
## **Description**
**Task**: [Designing and implementing buttons on main menu screen]
**Feature:** [Improving user experience]

Designing the visual elements such as start, tutorial, setting buttons
- The new buttons will appear on the main game screen, tutorial screen and setting screen.

## Dependencies
- None

## Milestones
List of steps that need to be completed for this task.
- [ ] Design new Start, Setting, Apply, Tutorial button (Sep. 24)
- [ ] Implement buttons(Start, Setting, Tutorial) on main menu screen (Sep. 25)
- [ ]  Implement buttons(Exit, Apply) on  Setting Screen (Sep. 25)
- [ ] Implement buttons(Exit) on  Tutorial Screen (Sep. 25)

## Members
- Yan Jiang (@whateverchris) (Yan Jiang)
- Aayush Aggarwal (@The-aayush)(Aayush)
- Runxing Li (@runx1ng) (Runxing Li)
- ZhiRan Huang (@ZhiRanHuang) (ZhiRan Huang(44811910))
- Jiaao Yu(@JiaaoY)(Jiaao)
