### ISSUE TITLE
Task Ticket - Create Tutorial for Ragnarok Racer Game

### ISSUE THREAD

**Issue by The-aayush** [UQdeco2800/2021-ext-studio-1#89]
## **Description**
**Task**: [Create Tutorial for Ragnarok Racer Game]
**Feature:** [Gives a description of game to the player]

Provides a description of the game to the player. Gives instructions about how to play the game.

## Dependencies
- [ ] Dependency 1: (#7) -- Information about Enemies
- [ ] Dependency 2: (#9) -- Information about Map Contents

## Milestones
List of steps that need to be completed for this task.
- [ ] Decide what should be on the page.(Sep. 20)
- [ ] Create a mock-up page.(Sep. 21)
- [ ] Applying the mock-up page(Sep. 22)
- [ ] Make improvements (adding more components, adding images) (Oct.3)

## Members
- Yan Jiang (@whateverchris) (Yan Jiang)
- Aayush Aggarwal (@The-aayush)(Aayush)
- Runxing Li (@runx1ng) (Runxing Li)
- ZhiRan Huang (@ZhiRanHuang) (ZhiRan Huang(44811910))
- Jiaao Yu(@JiaaoY)(Jiaao)

**Comment by manavvbahl** [comment]
https://github.com/UQdeco2800/2021-ext-studio-1/wiki/Enemies

**Comment by JiashengLi** [comment]
https://github.com/UQdeco2800/2021-ext-studio-1/wiki/Map-contents  Added features to the wiki pages so you can got the content's information into tutorial system
