### ISSUE TITLE
Map Contents

### ISSUE THREAD

**Issue by JiashengLi** [UQdeco2800/2021-ext-studio-1#9]
# **Description**
**Task:** Map content(#1).
**Feature:** Various elements in the map that affect the progress and interest of the game.
 
The purpose of this task is to enrich the interactive elements in the game map. The elements will be generated synchronously according to the generation of the map. Based on the current game mode, content will be classified into map props, map obstacles, map corners, and ground cracks.

The game relies on the basic map and player activities to operate, so the interaction in the map becomes extremely important. Players may pick up opportunity items to gain money, higher speed, shields against damage, or extra lives to reduce the difficulty of the game, and they can also use coherent game operations to avoid ground cracks or obstacles to obtain excitement and achievements. feel. In order to achieve good interaction, these randomly generated content need to be added to the most basic map.

In addition, the content of content may be different depending on the game mode. If it is a 2D horizontal game, it may increase the density of content generation.
 
## **Example (optional)**
- **Subway Surfer**: guide the player's route through consecutively generated gold coins. Barricades or stagnant subways are used as obstacles to enable players to choose their paths. At the same time, there are also props such as flying airbags that enable players to obtain special abilities.
 
# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.
 
- [ ] Dependency 1:Map generation (#10)-- the contents based on the map itself.
- [ ] Dependency 2:Player Interaction (#5)-- the contents will change the status of player.
- [ ] Dependency 3:Player Health System (#6) some contents may influence the health.

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 Design (Aug. 19) 
- [ ] Step 2 Implement(Aug. 25)
- [ ] Step 3 Test(Aug. 26)
- [ ] Step 4 UI/UX(Aug. 27)
 
**Completion Deadline:** Aug. 31
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Feiyu Chen (@fy3344)(Feiyu Chen)
- JiashengLi (@JiashengLi) (JIASHENG LI)
- Junyao Li (@lijunyao1) (Junyao Li)

**Comment by uqnjain** [comment]
The ticket looks good (continue to specify and add detail to the ticket as the sprint continues). Keep your ticket up to date to reflect progress. Look forward to reading about the development process of your feature on the wiki (Ensure you add the right links to the ticket)!

**Comment by LinzichangDing** [comment]
Hey guys, is your group responsible for obstacle movement?

**Comment by JiashengLi** [comment]
> Hey guys, is your group responsible for obstacle movement?
Yes, that's one of the map content

**Comment by LinzichangDing** [comment]
> Hey guys, is your group responsible for obstacle movement?
> Yes, that's one of the map content

The obstacles are not moving now right? May I ask when are you planning to complete the obstacle movement task? Because it's a bit hard for our team(player interaction) to implement some animations if your obstacles can't move.
