### ISSUE TITLE
Adding a timer to the Story Screen

### ISSUE THREAD

**Issue by SreehariRamesh** [UQdeco2800/2021-ext-studio-1#93]
## **Description**
**Task**: [Adding a timer to the story screen.]

Add a 15 seconds time window for the story screen before it is directed to the main game screen. This timer is not displayed on the story screen. If the user doesn't press the start button within 15 seconds, the game starts without input from the user. 

## Dependencies
- [ ] Dependency 1: (#82 ) -- Story Screen + Minor Adjustments/Tweaks

## Milestones
List of steps that need to be completed for this task.
- [x] Code the15 seconds timer into the story screen. (Sep  25)
- [x] Test the timer. (Sep  25)

## Members
- Sreehari Ramesh (@SreehariRamesh ) (Sreehari)
