### ISSUE TITLE
Redesign Bridge component to account for differences in screen entity grid system

### ISSUE THREAD

**Issue by AdrianLSY** [UQdeco2800/2021-ext-studio-1#95]
## **Description**
**Task**:  Add a way to rescale tile grids system coordinate into entity grid system

## Milestones
- [x] find correct coordinates for tile grid system
- [x] find correct coordinates for tile entity system
- [x] create/modify methods to rescale tile grid system to entity grid system
- [x] testing 

## Members
- Adrian Low (@AdrianLSY  )
