### ISSUE TITLE
Refactor some code from Team 1's Map content

### ISSUE THREAD

**Issue by AdrianLSY** [UQdeco2800/2021-ext-studio-1#99]
## Description
New bridge component methods return float values (previously int)

**Task**:  Refactor some methods in RainbowBridge.java

## Prerequisite
- [x] (#95 )

## Milestones
- [x] spawnObstables() cast lane.getMid() to int
- [x] spawnHealthObjects() cast lane.getMid() to int
- [x] spawnWeaponObjects() cast lane.getMid() to int
- [x] spawnCollectableObjects() cast lane.getMid() to int
- [x] testing 

## Members
- Adrian Low (@AdrianLSY  )
